### ISSUE TITLE
Build failed on Linux host for Windows 

### ISSUE THREAD

**Issue by ZerkerEOD** [MythicAgents/zippy#4]
Hello, when I go to build I get Err 2, ?Oh snap [Errno 2] No such file or directory: '/tmp/tmpojtn49m56e868818-688c-4576-8c47-0ff59c0c62ba/build/zippy_windows_x86_64.exe'"

This is on a fresh install, any ideas?

**Comment by jinncoder** [comment]
![screenshot](https://github.com/MythicAgents/zippy/assets/6900588/e1315618-9ee4-4ad5-9815-5244ab09e0c6)

Can you supply a screenshot like above - or other logs? I just installed from main - and it built on my end - hard to say what went wrong for you with out more details... :-(

The following would help:
 * Which version of Mythic
 * Which version of zippy
 * Logs / stdout / stderr
 * How'd you install zippy? ```sudo ./mythic-cli install github https://github.com/MythicAgents/zippy``` ?

**Comment by jinncoder** [comment]
Closing - pending more information...

**Comment by jinncoder** [comment]
@ZerkerEOD give it a spin with the latest changes
