### ISSUE TITLE
Building zippy payload for X64 failed

### ISSUE THREAD

**Issue by timukas** [MythicAgents/zippy#5]
Hello,

Using latest version of mythic & zippy.

Zippy was installed with this "./mythic-cli install github https://github.com/MythicAgents/zippy"

Building payload for x64 fails with - "**Unknown error while building payload. Check the stderr for this build. [Errno 2] No such file or directory: '/tmp/tmpzqe9uiv5d11b148c-08e6-4153-ab5b-8e8bac91f22c/build/zippy_linux_x86_64.elf'**
"

Below some screenshots from configuration and logs:

![image](https://github.com/MythicAgents/zippy/assets/1915618/593e37c5-6093-4562-b038-da81456fe225)

![image](https://github.com/MythicAgents/zippy/assets/1915618/ab7460c8-5c3c-4b18-9157-8515c4c16771)

![image](https://github.com/MythicAgents/zippy/assets/1915618/45d38293-31d4-4239-954d-0fab636d5573)

Any hints/ideas on how to build payload?

**Comment by jinncoder** [comment]
If the above code changes doesn't resolve the issue - re-open this issue and I'll look over it somemore ; )
